name: Update Calendar

on:
  schedule:
    - cron: '0 0 * * *' # Se lance tous les jours à minuit
  workflow_dispatch: # Permet de le lancer à la main pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add vitality_matches.ics
          git commit -m "Update calendar" || exit 0
          git push
